services:
  telegram-bot:
    image: secphoto:latest
    stdin_open: true   # docker run -i
    tty: true          # docker run -t
    container_name: telegram-secphoto
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}
      - TG_EXCLUDED_USERS=${TG_EXCLUDED_USERS}
      - TG_ARCHIVE_STATE_PATH=/app/data/archive_state.json
      - TG_COMMAND_CHANNEL_ID=${TG_COMMAND_CHANNEL_ID:-}
      - TZ=Europe/Berlin